# Generated by Django 5.2.4 on 2025-08-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message_attachment_alter_message_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
