# Generated by Django 5.2.4 on 2025-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_comment_options_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
