# Generated by Django 5.2.4 on 2025-08-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userdetails_last_seen_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='last_seen',
        ),
    ]
