# Generated by Django 5.2.4 on 2025-08-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_userdetails_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
